apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: replicated-design-system-dist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard