apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kots-component-library-dist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard