apiVersion: apps/v1
kind: Deployment
metadata:
  name: kots-component-library
spec:
  selector:
    matchLabels:
      app: kots-component-library
  replicas: 1
  template:
    metadata:
      labels:
        app: kots-component-library
    spec:
      containers:
      - name: kots-component-library
        image: okteto.dev/kots-component-library:latest
        ports:
        - containerPort: 8080